### ISSUE TITLE
Crear clase CalculadoraService

### ISSUE THREAD

**Issue by saulroc** [fatimabh18/calculadora#16]
En el directorio utilidades meter una clase CalculadoraService que tenga todo el código del Program.cs relacionado con el menú las opciones de usuario, etc, que tenga un método public void llamado Ejecutar que se llame desde Program.cs

**Comment by Carlosgv13** [comment]
#16

**Comment by saulroc** [comment]
No veo la clase calculadora service, solo veo que program se ha movido al directorio utilidades.

**Comment by Carlosgv13** [comment]
#16

**Comment by Carlosgv13** [comment]
#16
