### ISSUE TITLE
Además de escribir los resultados por la consola que los devuelvan los métodos

### ISSUE THREAD

**Issue by saulroc** [fatimabh18/calculadora#8]
https://github.com/fatimabh18/calculadora/blob/6314249a0a03c1c55c4381dd15af3c0f11d5cd00/Calculadora.cs#L5

Los métodos son void, vamos a cambiarlos para que devuelvan el resultado calculado además de escribirlo por la consola.

**Comment by Carlosgv13** [comment]
#8
