### ISSUE TITLE
La rama de trabajo va a ser dev

### ISSUE THREAD

**Issue by saulroc** [fatimabh18/calculadora#9]
La rama que tiene que tener los cambios debe ser dev, teneis la rama dev 4 cambios por delante de main y 3 por detrás, eso quiere decir que le habeís subido 3 cambios a main sin pasar por dev. Con un git merge debéis traeros esos cambios de main a dev para que nunca esté por detrás de main.

**Comment by Carlosgv13** [comment]
9#dev
